#!/usr/bin/env python3
"""Project selected raw Hook ABI facts from hookz's pinned Xahau macro.

The parser is hookz's Tree-sitter implementation.  This tool only selects a
reviewed incremental slice and renders provider-specific mechanical glue; rich
JavaScript lowering remains handwritten in cpp/provider/bindings/.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from hookz.wasm.whitelist import HookApiFunction, parse_hook_api_macro
from hookz.wasm.xahaud_ref import XAHAUD_COMMIT, vendored_root


ROOT = Path(__file__).resolve().parents[2]
POLICY = ROOT / "xahau" / "raw-hook-api-policy.json"
MACRO_REL = Path("include/xrpl/hook/hook_api.macro")
OUTPUTS = {
    ROOT / "python" / "jshookz" / "src" / "jshookz" / "generated_hook_raw.py": "python",
    ROOT / "cpp" / "provider" / "generated" / "hook_raw_imports.inc": "c-base",
    ROOT
    / "cpp"
    / "provider"
    / "generated"
    / "hook_raw_imports_consensus_entropy.inc": "c-entropy",
    ROOT / "xahau" / "generated" / "raw-hook-abi.json": "json",
}

BASELINE_PRODUCT = "provider"
CONSENSUS_ENTROPY_PRODUCT = "provider-consensus-entropy"


def _selected():
    policy = json.loads(POLICY.read_text())
    functions = parse_hook_api_macro(vendored_root() / MACRO_REL)
    by_name = {function.name: function for function in functions}
    names = policy["functions"]
    missing = [name for name in names if name not in by_name]
    if missing:
        raise SystemExit(f"policy names absent from pinned hook_api.macro: {missing}")
    selected = [by_name[name] for name in names]
    extension_rows = policy.get("experimental_extensions", [])
    extensions = []
    for row in extension_rows:
        name = row["name"]
        if name in by_name or any(function.name == name for function in selected):
            raise SystemExit(f"experimental extension duplicates base function: {name}")
        extensions.append(
            HookApiFunction(
                name=name,
                return_type=row["return_type"],
                param_types=tuple(row["param_types"]),
                amendment=row.get("amendment", ""),
            )
        )
    return policy, functions, selected, extensions


def _banner(comment: str, extensions) -> str:
    extension_note = ""
    if extensions:
        pins = ", ".join(
            f"{row['name']}@{row['source']['commit']}" for row in extensions
        )
        extension_note = f"; experimental {pins}"
    return (
        f"{comment} Generated by xahau/tools/generate_raw_hook_abi.py.\n"
        f"{comment} Xahau {XAHAUD_COMMIT}{extension_note}; "
        "edit raw-hook-api-policy.json, not this file.\n"
    )


def _python(selected, extensions, extension_rows) -> str:
    combined = [*selected, *extensions]
    rows = "\n".join(
        f"    ({fn.name!r}, {fn.return_type!r}, {fn.param_types!r}, {fn.amendment!r}),"
        for fn in combined
    )
    baseline_names = "\n".join(f"        {fn.name!r}," for fn in selected)
    entropy_names = "\n".join(f"        {fn.name!r}," for fn in combined)
    return (
        _banner("#", extension_rows)
        + f"\nRAW_HOOK_ABI = (\n{rows}\n)\n\n"
        + "RAW_HOOK_ABI_PRODUCT_NAMES = {\n"
        + f"    {BASELINE_PRODUCT!r}: (\n{baseline_names}\n    ),\n"
        + f"    {CONSENSUS_ENTROPY_PRODUCT!r}: (\n{entropy_names}\n    ),\n"
        + "}\n"
    )


def _c(selected, extensions) -> str:
    lines = [
        _banner("/*", extensions).replace("\n", " */\n").rstrip(" */\n") + " */",
        "",
    ]
    for fn in selected:
        params = (
            ", ".join(
                f"{ctype} arg{index}" for index, ctype in enumerate(fn.param_types)
            )
            or "void"
        )
        lines.extend(
            [
                f'__attribute__((import_module("env"), import_name("{fn.name}")))',
                f"extern {fn.return_type} hook_{fn.name}({params});",
                "",
            ]
        )
    return "\n".join(lines)


def _json_row(fn) -> dict:
    return {
        "name": fn.name,
        "return_type": fn.return_type,
        "param_types": list(fn.param_types),
        "amendment": fn.amendment or None,
        "wasm_signature": [hex(code) for code in fn.signature],
    }


def _json(all_functions, selected, extensions, extension_rows) -> str:
    payload = {
        "source": {
            "repository": "https://github.com/Xahau/xahaud",
            "commit": XAHAUD_COMMIT,
            "path": str(MACRO_REL),
            "macro_function_count": len(all_functions),
        },
        "experimental_extensions": extension_rows,
        "selected": [_json_row(fn) for fn in selected],
        "products": {
            BASELINE_PRODUCT: [_json_row(fn) for fn in selected],
            CONSENSUS_ENTROPY_PRODUCT: [
                _json_row(fn) for fn in (*selected, *extensions)
            ],
        },
    }
    return json.dumps(payload, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    policy, all_functions, selected, extensions = _selected()
    extension_rows = policy.get("experimental_extensions", [])
    renderers = {
        "python": lambda: _python(selected, extensions, extension_rows),
        "c-base": lambda: _c(selected, []),
        "c-entropy": lambda: _c(extensions, extension_rows),
        "json": lambda: _json(
            all_functions, selected, extensions, extension_rows
        ),
    }

    stale = []
    for path, kind in OUTPUTS.items():
        content = renderers[kind]()
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("stale generated raw ABI files: " + ", ".join(map(str, stale)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
