#!/usr/bin/env python3
"""Project selected raw Hook ABI facts from hookz's pinned Xahau macro.

The parser is hookz's Tree-sitter implementation.  This tool only selects a
reviewed incremental slice and renders provider-specific mechanical glue; rich
JavaScript lowering remains handwritten in wasm_bindings.c.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from hookz.wasm.whitelist import parse_hook_api_macro
from hookz.wasm.xahaud_ref import XAHAUD_COMMIT, vendored_root


ROOT = Path(__file__).resolve().parents[3]
POLICY = ROOT / "integrations" / "xahau" / "raw-hook-api-policy.json"
MACRO_REL = Path("include/xrpl/hook/hook_api.macro")
OUTPUTS = {
    ROOT / "packages" / "jshookz" / "src" / "jshookz" / "generated_hook_raw.py": "python",
    ROOT / "runtime" / "provider" / "generated" / "hook_raw_imports.inc": "c",
    ROOT / "codec" / "xrpl" / "host" / "generated" / "hook_raw_stubs.inc": "wasmtime",
    ROOT / "integrations" / "xahau" / "generated" / "raw-hook-abi.json": "json",
}


def _selected():
    policy = json.loads(POLICY.read_text())
    functions = parse_hook_api_macro(vendored_root() / MACRO_REL)
    by_name = {function.name: function for function in functions}
    names = policy["functions"]
    missing = [name for name in names if name not in by_name]
    if missing:
        raise SystemExit(f"policy names absent from pinned hook_api.macro: {missing}")
    return functions, [by_name[name] for name in names]


def _banner(comment: str) -> str:
    return (
        f"{comment} Generated by integrations/xahau/tools/generate_raw_hook_abi.py.\n"
        f"{comment} Xahau {XAHAUD_COMMIT}; edit raw-hook-api-policy.json, not this file.\n"
    )


def _python(selected) -> str:
    rows = "\n".join(
        f"    ({fn.name!r}, {fn.return_type!r}, {fn.param_types!r}, {fn.amendment!r}),"
        for fn in selected
    )
    return _banner("#") + f"\nRAW_HOOK_ABI = (\n{rows}\n)\n"


def _c(selected) -> str:
    lines = [_banner("/*").replace("\n", " */\n").rstrip(" */\n") + " */", ""]
    for fn in selected:
        params = ", ".join(
            f"{ctype} arg{index}" for index, ctype in enumerate(fn.param_types)
        ) or "void"
        lines.extend([
            f'__attribute__((import_module("env"), import_name("{fn.name}")))',
            f"extern {fn.return_type} hook_{fn.name}({params});",
            "",
        ])
    return "\n".join(lines)


def _wasmtime_kind(ctype: str) -> str:
    return {"int32_t": "WASM_I32", "uint32_t": "WASM_I32", "int64_t": "WASM_I64"}[ctype]


def _wasmtime(selected) -> str:
    lines = [_banner("//").rstrip(), ""]
    for fn in selected:
        params = ", ".join(_wasmtime_kind(t) for t in fn.param_types)
        returns = "" if fn.return_type == "void_t" else _wasmtime_kind(fn.return_type)
        try:
            handler = {
                "int32_t": "raw_hook_unavailable_i32_fn",
                "int64_t": "raw_hook_unavailable_i64_fn",
            }[fn.return_type]
        except KeyError:
            raise SystemExit(
                f"legacy Wasmtime fallback needs an explicit {fn.return_type} "
                f"policy before selecting {fn.name}"
            ) from None
        lines.append(
            f'reg(linker, "{fn.name}", {handler}, '
            f'{{{params}}}, {{{returns}}});'
        )
    return "\n".join(lines) + "\n"


def _json(all_functions, selected) -> str:
    payload = {
        "source": {
            "repository": "https://github.com/Xahau/xahaud",
            "commit": XAHAUD_COMMIT,
            "path": str(MACRO_REL),
            "macro_function_count": len(all_functions),
        },
        "selected": [
            {
                "name": fn.name,
                "return_type": fn.return_type,
                "param_types": list(fn.param_types),
                "amendment": fn.amendment or None,
                "wasm_signature": [hex(code) for code in fn.signature],
            }
            for fn in selected
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    all_functions, selected = _selected()
    renderers = {
        "python": lambda: _python(selected),
        "c": lambda: _c(selected),
        "wasmtime": lambda: _wasmtime(selected),
        "json": lambda: _json(all_functions, selected),
    }

    stale = []
    for path, kind in OUTPUTS.items():
        content = renderers[kind]()
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("stale generated raw ABI files: " + ", ".join(map(str, stale)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
