"""Build and seal the Xahau QuickJS provider."""

import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from . import paths


def _validate_native_abi(provider_imports: list[dict]) -> dict:
    raw_abi = json.loads(paths.XAHAU_RAW_HOOK_ABI.read_text())
    selected = raw_abi["selected"]
    by_name = {item["name"]: item for item in selected}
    provider_names = {item["name"] for item in provider_imports}
    if (
        len(by_name) != len(selected)
        or len(provider_names) != len(provider_imports)
        or len(provider_imports) != len(selected)
        or provider_names != set(by_name)
    ):
        raise ValueError(
            "sealed provider imports differ from the pinned raw Hook ABI snapshot"
        )
    return raw_abi


def wizer_executable() -> Path:
    """Resolve the Wizer binary. Env `WIZER` wins, then PATH, then cargo bin."""
    configured = os.environ.get("WIZER")
    if configured:
        path = Path(configured).expanduser()
        if not path.is_file():
            raise RuntimeError(f"WIZER={configured} is not a file")
        return path
    found = shutil.which("wizer")
    if found:
        return Path(found)
    cargo = Path.home() / ".cargo" / "bin" / "wizer"
    if cargo.is_file():
        return cargo
    raise RuntimeError(
        "wizer not found. Install bytecodealliance/wizer 10 and put it on PATH "
        "or set WIZER=/path/to/wizer"
    )


def wizer_provider(src: Path, dest: Path) -> Path:
    """Cold wasm → sealed wasm. `src` is left alone."""
    if src.resolve() == dest.resolve():
        raise RuntimeError("wizer src and dest must differ; do not snapshot in place")
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_name(dest.name + ".wizer-tmp")
    run(
        [
            wizer_executable(),
            "--keep-init-func",
            "true",
            "--rename-func",
            "_initialize=wizer.initialize",
            "-o",
            tmp,
            src,
        ]
    )
    if not tmp.is_file():
        raise RuntimeError(f"wizer produced no output at {tmp}")
    if tmp.stat().st_size <= src.stat().st_size:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(
            f"wizer output is not larger than the input "
            f"({tmp.stat().st_size} <= {src.stat().st_size}); snapshot looks vacuous"
        )
    tmp.replace(dest)
    return dest


def run(cmd: list[str | Path], **kwargs) -> subprocess.CompletedProcess:
    """Run a command, printing it first."""
    print(f"$ {' '.join(str(c) for c in cmd)}")
    return subprocess.run([str(c) for c in cmd], check=True, **kwargs)


def seal_xahau_hook_provider_bundle(
    wasm_path: Path = paths.XAHAU_HOOK_PROVIDER_WASM,
    lock_path: Path = paths.XAHAU_RUNTIME_PROFILE_LOCK,
    manifest_path: Path = paths.XAHAU_HOOK_PROVIDER_MANIFEST,
    cmake_manifest_path: Path = paths.XAHAU_HOOK_PROVIDER_CMAKE_MANIFEST,
    native_abi_path: Path = paths.XAHAU_HOOK_PROVIDER_NATIVE_ABI,
) -> Path:
    """Verify and emit the manifest consumed by Xahau's native build."""
    from .runtime_profile import verify_runtime_profile_lock

    profile = verify_runtime_profile_lock(lock_path, wasm_path)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(lock_path, manifest_path)
    data = profile.data
    source = data["source"]
    provider = data["provider"]
    provider_imports = provider["imports"]
    native_abi = _validate_native_abi(provider_imports)
    native_abi_path.parent.mkdir(parents=True, exist_ok=True)
    native_abi_path.write_text(
        json.dumps(native_abi, sort_keys=True, separators=(",", ":")) + "\n"
    )
    manifest_sha256 = hashlib.sha256(manifest_path.read_bytes()).hexdigest()
    native_abi_sha256 = hashlib.sha256(native_abi_path.read_bytes()).hexdigest()
    cmake_manifest_path.write_text(
        "# Generated by jshookz build provider; do not edit.\n"
        f'set(XAHAU_QUICKJS_MANIFEST_SCHEMA "{data["schema"]}")\n'
        f'set(XAHAU_QUICKJS_MANIFEST_SHA256 "{manifest_sha256}")\n'
        f'set(XAHAU_QUICKJS_PROVIDER_FILE "{wasm_path.name}")\n'
        f'set(XAHAU_QUICKJS_PROVIDER_SHA256 "{provider["sha256"]}")\n'
        f'set(XAHAU_QUICKJS_PROVIDER_SIZE "{provider["size"]}")\n'
        f'set(XAHAU_QUICKJS_PROVIDER_IMPORT_COUNT "{len(provider_imports)}")\n'
        f'set(XAHAU_QUICKJS_NATIVE_ABI_FILE "{native_abi_path.name}")\n'
        f'set(XAHAU_QUICKJS_NATIVE_ABI_SHA256 "{native_abi_sha256}")\n'
        f'set(XAHAU_QUICKJS_BYTECODE_ABI_ID "{data["bytecode_abi_id"]}")\n'
        f'set(XAHAU_QUICKJS_RUNTIME_PROFILE_ID "{data["runtime_profile_id"]}")\n'
        f'set(XAHAU_QUICKJS_HOOK_API_VERSION "{source["artifact"]["hook_api_version"]}")\n'
        f'set(XAHAU_QUICKJS_WASMTIME_VERSION "{source["engine"]["version"]}")\n'
        f'set(XAHAU_QUICKJS_INITIALIZATION_FUEL "{source["limits"]["wasmtime_fuel_per_initialization"]}")\n'
        f'set(XAHAU_QUICKJS_INVOCATION_FUEL "{source["limits"]["wasmtime_fuel_per_invocation"]}")\n'
        f'set(XAHAU_QUICKJS_HOST_WORK_METER "{source["limits"]["host_work_meter"]}")\n'
        f'set(XAHAU_QUICKJS_HOST_WORK_BUDGET "{source["limits"]["host_work_budget"]}")\n'
        f'set(XAHAU_QUICKJS_HOST_WORK_BASE_PER_CALL "{source["limits"]["host_work_base_per_call"]}")\n'
        f'set(XAHAU_QUICKJS_HOST_WORK_PER_ADDRESSED_BYTE "{source["limits"]["host_work_per_addressed_byte"]}")\n'
        f'set(XAHAU_QUICKJS_HOST_ADAPTER_POLICY "{source["execution"]["host_adapter_policy"]}")\n'
        f'set(XAHAU_QUICKJS_HEAP_BYTES "{source["limits"]["quickjs_heap_bytes"]}")\n'
        f'set(XAHAU_QUICKJS_STACK_BYTES "{source["limits"]["quickjs_stack_bytes"]}")\n'
    )
    print(f"✓ Sealed {manifest_path}")
    print(f"✓ Projected {cmake_manifest_path}")
    return manifest_path


def build_xahau_hook_provider(*, wizer: bool = True) -> Path:
    """Build and seal the deterministic Xahau QuickJS provider bundle."""
    paths.require_source_checkout()
    if not paths.WASI_SDK_PATH.exists():
        print(f"error: wasi-sdk not found at {paths.WASI_SDK_PATH}", file=sys.stderr)
        print("install via: mise install wasi-sdk@32", file=sys.stderr)
        sys.exit(1)

    build_dir = paths.XAHAU_PROVIDER_BUILD_DIR
    build_dir.mkdir(parents=True, exist_ok=True)
    run(
        [
            "cmake",
            "-B",
            build_dir,
            "-S",
            paths.PROVIDER_SRC,
            f"-DCMAKE_TOOLCHAIN_FILE={paths.WASI_TOOLCHAIN}",
            "-DCMAKE_BUILD_TYPE=Release",
            "-DXAHAU_HOOK_PROVIDER=ON",
        ]
    )
    run(["cmake", "--build", build_dir])

    cold = paths.XAHAU_HOOK_PROVIDER_UNWIZERED_WASM
    wasm = paths.XAHAU_HOOK_PROVIDER_WASM
    if not cold.exists():
        raise RuntimeError(f"Xahau Hook provider not found at {cold}")
    if wizer:
        wizer_provider(cold, wasm)
        print(f"✓ Wizered {wasm} ({wasm.stat().st_size / (1024 * 1024):.1f} MB)")
        seal_xahau_hook_provider_bundle()
    else:
        shutil.copyfile(cold, wasm)
        print(f"✓ Skipped Wizer (--no-wizer); copied {cold.name}")
    print(f"\n✓ Built {wasm} ({wasm.stat().st_size / (1024 * 1024):.1f} MB)")
    return wasm
