# Generated by xahau/tools/generate_raw_hook_abi.py.
# Xahau bb244ef7729503a0317bcff0f8fdaa93ca5cb7d2; edit raw-hook-api-policy.json, not this file.

RAW_HOOK_ABI = (
    ('accept', 'int64_t', ('uint32_t', 'uint32_t', 'int64_t'), ''),
    ('rollback', 'int64_t', ('uint32_t', 'uint32_t', 'int64_t'), ''),
    ('ledger_seq', 'int64_t', (), ''),
    ('ledger_last_time', 'int64_t', (), ''),
    ('ledger_last_hash', 'int64_t', ('uint32_t', 'uint32_t'), ''),
    ('ledger_nonce', 'int64_t', ('uint32_t', 'uint32_t'), ''),
    ('otxn_type', 'int64_t', (), ''),
    ('otxn_param', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('otxn_slot', 'int64_t', ('uint32_t',), ''),
    ('slot_set', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('slot_size', 'int64_t', ('uint32_t',), ''),
    ('slot', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('slot_clear', 'int64_t', ('uint32_t',), ''),
    ('hook_account', 'int64_t', ('uint32_t', 'uint32_t'), ''),
    ('hook_param', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('trace', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('state', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('state_foreign', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t', 'uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('state_set', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
    ('prepare', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), 'featureHooksUpdate2'),
    ('etxn_reserve', 'int64_t', ('uint32_t',), ''),
    ('emit', 'int64_t', ('uint32_t', 'uint32_t', 'uint32_t', 'uint32_t'), ''),
)
