#!/usr/bin/env python3
"""Generate provider-static serialized-object limits from a runtime profile."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


LIMITS = (
    "serialized_object_max_bytes",
    "serialized_object_max_fields",
    "serialized_object_max_scopes",
    "serialized_object_max_depth",
)
SCHEMA = "xahau.quickjs.runtime-profile-source.v1"
UINT32_MAX = (1 << 32) - 1


def profile_limits(source: bytes) -> dict[str, int]:
    document = json.loads(source)
    if not isinstance(document, dict) or document.get("schema") != SCHEMA:
        raise ValueError(f"runtime profile must use schema {SCHEMA!r}")
    limits = document.get("limits")
    if not isinstance(limits, dict):
        raise ValueError("runtime profile has no limits object")

    selected: dict[str, int] = {}
    for name in LIMITS:
        value = limits.get(name)
        if (
            not isinstance(value, int)
            or isinstance(value, bool)
            or value <= 0
            or value > UINT32_MAX
        ):
            raise ValueError(
                f"runtime profile limit {name!r} must be a positive uint32"
            )
        selected[name] = value
    return selected


def render(source: bytes, source_name: str) -> str:
    values = profile_limits(source)
    digest = hashlib.sha256(source).hexdigest()
    constants = "\n".join(
        f"inline constexpr std::uint32_t {name} = {values[name]}u;" for name in LIMITS
    )
    return f"""// Auto-generated file. DO NOT EDIT.
// Generated by scripts/generate_runtime_profile_limits.py.
// Source: {source_name}
// SHA-256: {digest}

#pragma once

#include <cstdint>

namespace catl::xdata::xahau_profile_limits {{

{constants}

}} // namespace catl::xdata::xahau_profile_limits
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    source = args.input.read_bytes()
    args.output.write_text(render(source, args.input.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
