#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""
Generate C++ embedded definitions headers from server_definitions JSON files.

Outputs constexpr char arrays (no std::string heap allocation) suitable for
WASM where static init must not touch the heap.

Usage:
  python generate_definitions.py \
    --input definitions/xahau_definitions.json \
    --output generated/embedded_xahau_definitions.h \
    --namespace catl::xdata::xahau

  python generate_definitions.py \
    --input definitions/xrpl_definitions.json \
    --output generated/embedded_xrpl_definitions.h \
    --namespace catl::xdata::xrpl
"""

import json
import sys
import argparse
import hashlib
from pathlib import Path

# Annex B recommends compilers accept at least 65,536 characters in one
# string literal. Stay well under that so adjacent raw tokens remain
# portable. C++ concatenates adjacent literals at compile time.
LITERAL_CHUNK_LIMIT = 32768


def clean_definitions(defs: dict) -> dict:
    """Clean up known issues in server definitions."""

    # Remove duplicate "hash" field — the definitions have it twice:
    # once as non-serialized (nth=257) and once as serialized (nth=1).
    # The serialized one shadows the non-serialized one and causes issues.
    if "FIELDS" in defs:
        seen_names = set()
        cleaned = []
        for entry in defs["FIELDS"]:
            name = entry[0]
            if name in seen_names:
                print(f"  Removed duplicate field: {name}", file=sys.stderr)
                continue
            seen_names.add(name)
            cleaned.append(entry)
        defs["FIELDS"] = cleaned

    # Strip the bulky "features" section — not needed for codec operations
    if "features" in defs:
        n = len(defs["features"])
        del defs["features"]
        print(f"  Stripped {n} feature entries (not needed for codec)", file=sys.stderr)

    return defs


def split_raw_string_chunks(
    payload: str, limit: int = LITERAL_CHUNK_LIMIT
) -> list[str]:
    """Split payload into chunks that each stay under ``limit`` characters."""
    if limit <= 0:
        raise ValueError("limit must be positive")
    if not payload:
        return [""]
    return [payload[i : i + limit] for i in range(0, len(payload), limit)]


def emit_adjacent_raw_literals(chunks: list[str]) -> str:
    """Emit adjacent R\"json(...)json\" tokens for compile-time concatenation."""
    return "\n".join(f'    R"json({chunk})json"' for chunk in chunks)


def generate_header(json_str: str, namespace: str,
                    source_name: str = "unknown",
                    source_sha: str = "unknown") -> str:
    """Generate a C++ header with a constexpr char array.

    Output is deterministic: identical input gives a byte-identical header.
    This used to stamp datetime.now(), which meant every run produced a new
    file. The header is committed AND generated by the build, so a wall-clock
    stamp dirtied the tree and recompiled embedded_protocol.cpp on every build.
    The input's hash is the provenance actually worth recording anyway.

    Payloads larger than Annex B's 65536-character recommendation are split
    into adjacent raw-string tokens of at most LITERAL_CHUNK_LIMIT characters.
    The compiler concatenates them; the array contents stay identical to
    ``json_str`` plus the terminating NUL. Do not switch to std::string.
    """
    chunks = split_raw_string_chunks(json_str)
    literals = emit_adjacent_raw_literals(chunks)
    return f"""// Auto-generated file. DO NOT EDIT.
// Generated from server definitions JSON by scripts/generate_definitions.py.
// The build regenerates this -- see x-data/definitions.cmake.
// Source: {source_name}
// SHA-256: {source_sha}
//
// constexpr char array — no heap allocation at static init time.
// Safe for WASM where _initialize must not fragment the heap.
// Adjacent raw-string tokens stay under {LITERAL_CHUNK_LIMIT} chars
// (Annex B recommends compilers accept at least 65536 in one literal).

#pragma once

namespace {namespace} {{

inline constexpr char EMBEDDED_DEFINITIONS[] =
{literals};

}} // namespace {namespace}
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ embedded definitions from server_definitions JSON"
    )
    parser.add_argument("--input", type=Path, required=True, help="Input JSON file")
    parser.add_argument("--output", type=Path, required=True, help="Output C++ header")
    parser.add_argument("--namespace", default="catl::xdata", help="C++ namespace")
    parser.add_argument("--no-clean", action="store_true", help="Skip cleanup (duplicates, features)")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: {args.input} not found", file=sys.stderr)
        sys.exit(1)

    with open(args.input) as f:
        defs = json.load(f)

    print(f"Loaded {args.input}: {len(defs.get('FIELDS', []))} fields, "
          f"{len(defs.get('TRANSACTION_TYPES', {}))} tx types", file=sys.stderr)

    if not args.no_clean:
        defs = clean_definitions(defs)

    # Compact JSON — no whitespace
    json_str = json.dumps(defs, separators=(",", ":"))
    print(f"  JSON size: {len(json_str)} bytes", file=sys.stderr)
    chunks = split_raw_string_chunks(json_str)
    if len(chunks) > 1:
        print(
            f"  split into {len(chunks)} adjacent raw literals "
            f"(<= {LITERAL_CHUNK_LIMIT} chars each)",
            file=sys.stderr,
        )

    if ")json" in json_str:
        print("Error: input contains the raw-string delimiter )json — the "
              "literal would terminate early", file=sys.stderr)
        sys.exit(1)

    # Hash the bytes on disk, so the stamp identifies the actual input file.
    source_sha = hashlib.sha256(args.input.read_bytes()).hexdigest()
    header = generate_header(json_str, args.namespace, args.input.name, source_sha)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        f.write(header)

    print(f"  Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
